### ISSUE TITLE
Elaspic2 can't really be pip install'ed

### ISSUE THREAD

**Issue by xrobin** [elaspic/elaspic2#1]
Running Python Python 3.8.5 on Ubuntu Focal.

I tried to install elaspic2 with the pip install command from the README.md file.

    pip install elaspic2

The installation was apparently successful and the following dependencies were pulled:

    Successfully installed Send2Trash-1.5.0 argon2-cffi-20.1.0 astunparse-1.6.3 async-generator-1.10 biopython-1.78 bleach-3.3.0 brotlipy-0.7.0 cffi-1.14.5 defusedxml-0.6.0 elaspic2-0.1.7 fire-0.3.1 ipykernel-5.5.0 ipywidgets-7.6.3 jinja2-2.11.3 jsonschema-3.2.0 jupyter-client-6.1.11 jupyter-core-4.7.1 jupyterlab-pygments-0.1.2 jupyterlab-widgets-1.0.0 mdtraj-1.9.5 mistune-0.8.4 mmtf-python-1.1.2 msgpack-1.0.2 nbclient-0.5.2 nbconvert-6.0.7 nbformat-5.1.2 nest-asyncio-1.5.1 nglview-2.7.7 notebook-6.2.0 packaging-20.9 pandocfilters-1.4.3 paramiko-2.7.2 prometheus-client-0.9.0 ptyprocess-0.7.0 pycparser-2.20 pygments-2.8.0 pyparsing-2.4.7 pyrsistent-0.17.3 pyzmq-22.0.3 tenacity-6.2.0 termcolor-1.1.0 terminado-0.9.2 testpath-0.4.4 tornado-6.1 tqdm-4.54.1 webencodings-0.5.1 widgetsnbextension-3.5.1

However the `kmbio` and `kmtools` are also required and haven't been  installed:

```
python3 -m elaspic2
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/xavier/.local/lib/python3.8/site-packages/elaspic2/__init__.py", line 4, in <module>
    from kmbio.PDB.core import Atom
ModuleNotFoundError: No module named 'kmbio'
```

Expected outcome:

- the README.md file states the extra dependencies that must be installed separately
- OR the README.md doesn't mention the pip installation
- OR `kmbio` and `kmtools` are made available on PyPI and installed automatically.

**Comment by ostrokach** [comment]
Sorry for the late reply! I somehow missed this message in my inbox.

Thank you for bringing the issue to our attention. In our lab, we use `conda` almost exclusively, which makes it difficult to make sure that the `pip` dependencies that we have listed are accurate and up to date.

I have updated the `pip` installation guide provided in the `README.md` file to something that is currently known to work. Furthermore, I have added a CI pipeline that uses `pip` to install `elaspic2` using the exact same code that is provided in the `README.md` file and the demo notebooks. This pipeline is scheduled to run every month and will hopefully pick up any breakage or drift in dependencies (you can see the last run here: https://gitlab.com/elaspic/elaspic2/-/jobs/1132624338).

Thanks again for your interest!
